services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - learnwell_cms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_ADMIN_PASSWORD}
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq_data:/data
    networks:
      - learnwell_cms_network

  api:
    build:
      context: ./src/Backend/LearnWellUniversity_CMS
      dockerfile: LearnWellUniversity_CMS.API/Dockerfile
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpiryMinutes: ${JWT_EXPIRY_MINUTES}
      Seq__Url: "http://seq:5341"
    depends_on:
      db:
        condition: service_healthy
      seq:
        condition: service_started
    networks:
      - learnwell_cms_network

  ui:
    build:
      context: ./src/Frontend/learnwell_cms_ui
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - learnwell_cms_network

networks:
  learnwell_cms_network:
    driver: bridge

volumes:
  postgres_data:
  seq_data: